name: Java

on:
  workflow_call:
    inputs:
      modules:
        description: 'Java version to use'
        type: string
        required: true

jobs:
  build-go:
    runs-on: ubuntu-22.04
    steps:
      - name: test
        run: |
          echo ${{ inputs.modules }}