name: Java

on:
  workflow_call:
    inputs:
      modules:
        description: 'modules and versions to use'
        type: string
        required: true

jobs:
  build-java:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        modules: ${{ fromJSON(inputs.modules) }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: generated-code-${{ matrix.modules.module }}
        working-directory: "${{ github.workspace }}/gen"

      - name: Pull module repository
        uses: actions/checkout@v3
        with:
          repository: "StephanePaulus/go-${{ matrix.modules.module }}-library"
          path: "${{ github.workspace }}/gen/go"
          ref: main
          fetch-depth: 0

      - name: Test
        working-directory: ${{ github.workspace }}
        run: |
          ls -la

      - name: Set git config
        working-directory: ${{ github.workspace }}/gen/go
        run: |
          ls -la
          git config user.name stephane
          git config user.email stephane.paulus@gmail.com

      - name: Push generated go code
        id: commit-to-gitops-repo
        working-directory: ${{ github.workspace }}/gen/go
        run: |
          ls -la
          COMMIT_MESSAGE="Update generated code"
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE"
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
          
          git add .
          git commit -m "$COMMIT_MESSAGE"
          git push
