# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: release-build

on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  packages: write

jobs:
  example_matrix:
    runs-on: ubuntu-latest
    outputs:
      module: ${{ steps.split.outputs._0 }}
      version: ${{ steps.split.outputs._1 }}
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v3

      - uses: jungwinter/split@v2
        id: split
        with:
          separator: '-'
          msg: ${{ github.ref_name }}
      # Install the `buf` CLI
      - uses: bufbuild/buf-setup-action@v1.19.0
      # Ensure that `buf` is installed
      - run: |
          buf generate ${{ steps.split.outputs._0 }}/proto
      - name: Archive generated code
        uses: actions/upload-artifact@v3
        with:
          name: generated-code-${{ steps.split.outputs._0 }}
          path: gen/

  build-java:
    runs-on: ubuntu-22.04
    needs: [example_matrix]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: generated-code-${{ needs.example_matrix.outputs.module }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd gen/java
          ./gradlew publish -DrootProjectName=${{ needs.example_matrix.outputs.module }} -Pversion=${{ needs.example_matrix.outputs.version }}
          

  build-go:
    runs-on: ubuntu-22.04
    needs: [example_matrix]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: generated-code-${{ needs.example_matrix.outputs.module }}

      - name: Pull module repository
        uses: actions/checkout@v3
        with:
          repository: "StephanePaulus/go-${{ matrix.modules.module }}-library"
          path: "${{ github.workspace }}/generated-repo"
          ref: main
          fetch-depth: 0
          token: ${{ secrets.PUSH_SECRET }}


      - name: Set git config
        working-directory: ${{ github.workspace }}/generated-repo
        run: |
          git config user.name stephane
          git config user.email stephane.paulus@gmail.com

      - name: Push generated go code
        id: commit-to-gitops-repo
        working-directory: ${{ github.workspace }}/generated-repo
        run: |
          rm -rf ${{ needs.example_matrix.outputs.module }}
          mv ../go/* .
          COMMIT_MESSAGE="Update generated code"
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE"
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
          
          git add .
          git commit -m "$COMMIT_MESSAGE" --allow-empty
          git tag v${{ needs.example_matrix.outputs.version }}
          git push
